name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
      - dev
jobs:
  alpine-clang:
    name: "alpine-${{ matrix.alpine_version }} [clang-10]"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        alpine_version: [3.13]
        build_shared_lib: [on, off]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Container
        run: |
          sudo docker build --build-arg alpine_version=${{ matrix.alpine_version }} \
                            --build-arg build_shared_lib=${{ matrix.build_shared_lib }} \
                            -f docker/alpine/clang.Dockerfile \
                            --tag=xalwart.base-test:alpine-clang .
      - name: Run Tests
        run: |
          sudo docker run xalwart.base-test:alpine-clang
  alpine-gcc:
    name: "alpine-${{ matrix.alpine_version }} [gcc-10]"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        alpine_version: [3.13]
        build_shared_lib: [on, off]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Container
        run: |
          sudo docker build --build-arg alpine_version=${{ matrix.alpine_version }} \
                            --build-arg build_shared_lib=${{ matrix.build_shared_lib }} \
                            -f docker/alpine/gcc.Dockerfile \
                            --tag=xalwart.base-test:alpine-gcc .
      - name: Run Tests
        run: |
          sudo docker run xalwart.base-test:alpine-gcc
  ubuntu-clang:
    name: "${{ matrix.os }} [clang-${{ matrix.compiler_version }}]"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        compiler_version: [10]
        build_shared_lib: [on, off]
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler
        run: |
          sudo apt update -y && \
          sudo pip install --upgrade cmake && \
          sudo apt install -y clang-${{ matrix.compiler_version }} valgrind
      - name: Build and Install Google Test Framework
        run: |
          git clone -q https://github.com/google/googletest.git && \
          sudo mkdir -p ./googletest/build && \
          cd ./googletest/build && \
          sudo cmake -DCMAKE_CXX_COMPILER=clang++-${{ matrix.compiler_version }} \
                     -DCMAKE_C_COMPILER=clang-${{ matrix.compiler_version }} .. && \
          sudo make && \
          sudo make install
      - name: Build Tests
        run: |
          sudo mkdir build && \
          cd build/ && \
          sudo cmake -DCMAKE_CXX_COMPILER=clang++-${{ matrix.compiler_version }} \
                     -DCMAKE_C_COMPILER=clang-${{ matrix.compiler_version }} \
                     -DCMAKE_BUILD_TYPE=Debug \
                     -DBUILD_SHARED_LIB=${{ matrix.build_shared_lib }} \
                     .. && \
          sudo make unittests-all
      - name: Run Tests
        run: |
          sudo valgrind --leak-check=full ./build/tests/unittests-all
  ubuntu-gcc:
    name: "${{ matrix.os }} [gcc-${{ matrix.compiler_version }}]"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        compiler_version: [10]
        build_shared_lib: [on, off]
    steps:
      - uses: actions/checkout@v2
      - name: Install Compiler and Check Version
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
          sudo apt update -y && \
          sudo pip install --upgrade cmake && \
          sudo apt install -y gcc-${{ matrix.compiler_version }} g++-${{ matrix.compiler_version }} valgrind && \
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.compiler_version }} 10 && \
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.compiler_version }} 10 && \
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30 && \
          sudo update-alternatives --set cc /usr/bin/gcc && \
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30 && \
          sudo update-alternatives --set c++ /usr/bin/g++ && \
          gcc --version && \
          g++ --version
      - name: Build and Install Google Test Framework
        run: |
          git clone -q https://github.com/google/googletest.git && \
          sudo mkdir -p ./googletest/build && \
          cd ./googletest/build && \
          sudo cmake -DCMAKE_CXX_COMPILER=g++-${{ matrix.compiler_version }} \
                     -DCMAKE_C_COMPILER=gcc-${{ matrix.compiler_version }} .. && \
          sudo make && \
          sudo make install
      - name: Build Tests
        run: |
          sudo mkdir build && \
          cd build/ && \
          sudo cmake -DCMAKE_CXX_COMPILER=g++-${{ matrix.compiler_version }} \
                     -DCMAKE_C_COMPILER=gcc-${{ matrix.compiler_version }} \
                     -DCMAKE_BUILD_TYPE=Debug \
                     -DBUILD_SHARED_LIB=${{ matrix.build_shared_lib }} \
                     .. && \
          sudo make unittests-all
      - name: Run Tests
        run: |
          sudo valgrind --leak-check=full ./build/tests/unittests-all
