name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
      - dev
jobs:
  test:
    name: "${{ matrix.os }} [${{ matrix.compiler }}-${{ matrix.compiler_version }}] [shared: ${{ matrix.build_shared_lib }}]"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os: [ "alpine-3.13", "ubuntu-18.04", "ubuntu-20.04" ]
        compiler: [ clang, gcc ]
        compiler_version: [ 10 ]
        build_shared_lib: [ on, off ]
    steps:
      - uses: actions/checkout@v2
      - name: Generate Dockerfile
        run: |
          python docker/compile.py --os=${{ matrix.os }} \
                                   --compiler=${{ matrix.compiler }}-${{ matrix.compiler_version }} \
                                   --out=./test.Dockerfile
      - name: Build the Container
        run: |
          sudo docker build --build-arg build_shared_lib=${{ matrix.build_shared_lib }} \
                            -f ./test.Dockerfile \
                            --tag=xalwart.base:test-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.compiler_version }} .
      - name: Run Tests
        run: |
          sudo docker run xalwart.base:test-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
