name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - release
jobs:
  linux-build:
    name: Build the library for Linux and upload it to artifacts
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: alpine
            version: 3.13
          - name: ubuntu
            version: 18.04
        compiler: [ gcc, clang ]
        compiler_version: [ 10 ]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Library
        run: |
          sudo docker run -i \
                          -v ${{ github.workspace }}:/app \
                          xalwart/${{ matrix.compiler }}:${{ matrix.compiler_version }}-${{ matrix.os.name }}-${{ matrix.os.version }} \
                          bash /app/scripts/linux/build.sh ${{ matrix.os.name }} ${{ matrix.compiler }} ${{ matrix.compiler_version }}
      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xalwart.base-${{ matrix.os.name }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
          path: xalwart.base-${{ matrix.os.name }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
          retention-days: 60
  linux-test:
    name: "Testing: ${{ matrix.os.name }}-${{ matrix.os.version }} [${{ matrix.compiler }}-${{ matrix.compiler_version }}]"
    needs: [ linux-build ]
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: alpine
            version: 3.13
          - name: ubuntu
            version: 18.04
          - name: ubuntu
            version: 20.04
        compiler: [ clang, gcc ]
        compiler_version: [ 10 ]
    steps:
      - uses: actions/checkout@v2
      - name: Download the Artifact
        uses: actions/download-artifact@v2
        with:
          name: xalwart.base-${{ matrix.os.name }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
          path: xalwart.base-${{ matrix.os.name }}-${{ matrix.compiler }}-${{ matrix.compiler_version }}
      - name: Build and Run Tests
        run: |
          sudo docker run -i \
                          -v ${{ github.workspace }}:/app \
                          xalwart/gtest:1.11.0-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.os.name }}-${{ matrix.os.version }} \
                          bash /app/scripts/linux/test.sh ${{ matrix.os.name }} ${{ matrix.compiler }} ${{ matrix.compiler_version }}
  macos-build:
    name: Build the library for macOS and upload it to artifacts
    runs-on: ${{ matrix.os_name }}-${{ matrix.os_version }}
    strategy:
      fail-fast: false
      matrix:
        os_name: [ macos ]
        os_version: [ 10.14, 10.15, 11 ]
        step:
          - compiler:
              cc: gcc-10
              cxx: g++-10
          - compiler:
              cc: clang
              cxx: clang++
    steps:
      - uses: actions/checkout@v2
      - name: Build the Library
        run: |
          mkdir build && cd build
          cmake -D CMAKE_BUILD_TYPE=Release \
                -D CMAKE_C_COMPILER=${{ matrix.step.compiler.cc }} \
                -D CMAKE_CXX_COMPILER=${{ matrix.step.compiler.cxx }} \
                ..
          sudo mkdir -p /usr/local/include && sudo mkdir -p /usr/local/lib
          make xalwart.base && sudo make install
          cd && mkdir target-build && cd target-build
          mkdir -p include && mkdir -p lib && cd
          cp -r /usr/local/include/xalwart.base target-build/include
          cp -r /usr/local/lib/libxalwart.base* target-build/lib
      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xalwart.base-${{ matrix.os_name }}-${{ matrix.os_version }}-${{ matrix.step.compiler.cc }}
          path: target-build
          retention-days: 60
  macos-test:
    name: "Testing: ${{ matrix.os_name }}-${{ matrix.os_version }} [${{ matrix.step.compiler.cc }}]"
    needs: [ macos-build ]
    runs-on: ${{ matrix.os_name }}-${{ matrix.os_version }}
    strategy:
      fail-fast: false
      matrix:
        os_name: [ macos ]
        os_version: [ 10.14, 10.15, 11 ]
        step:
          - compiler:
              cc: gcc-10
              cxx: g++-10
          - compiler:
              cc: clang
              cxx: clang++
    steps:
      - uses: actions/checkout@v2
      - name: Install Valgrind
        run: |
          brew tap LouisBrunner/valgrind
          brew install --HEAD LouisBrunner/valgrind/valgrind
      - name: Install Google Test Framework
        run: |
          brew install googletest
      - name: Create Target Directories
        run: |
          sudo mkdir -p /usr/local
      - name: Download the Artifact
        uses: actions/download-artifact@v2
        with:
          name: xalwart.base-${{ matrix.os_name }}-${{ matrix.os_version }}-${{ matrix.step.compiler.cc }}
          path: /usr/local
      - name: Build and Run Tests
        run: |
          mkdir build && cd build
          cmake -D CMAKE_C_COMPILER=${{ matrix.step.compiler.cc }} \
                -D CMAKE_CXX_COMPILER=${{ matrix.step.compiler.cxx }} \
                -D CMAKE_BUILD_TYPE=Release \
                -D XW_BUILD_LIB=OFF \
                -D XW_BUILD_TESTS=ON \
                ..
          make unittests-all
          valgrind --leak-check=full ./tests/unittests-all
