name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
      - dev
jobs:
  compile-lib:
    name: Build the library and upload it to artifacts
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: alpine
            version: 3.13
          - name: ubuntu
            version: 18.04
        lib_type: [ shared, static ]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Library
        run: |
          sudo docker run -i \
                          -v ${{ github.workspace }}:/app \
                          xalwart/clang:10-${{ matrix.os.name }}-${{ matrix.os.version }} \
                          bash /app/misc/build.sh ${{ matrix.os.name }} ${{ matrix.lib_type }} clang
      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xalwart.base-${{ matrix.lib_type }}-${{ matrix.os.name }}
          path: xalwart.base-${{ matrix.lib_type }}-${{ matrix.os.name }}
          retention-days: 90
  test:
    name: "${{ matrix.os.name }}-${{ matrix.os.version }} [${{ matrix.compiler }}-${{ matrix.compiler_version }}] [${{ matrix.lib_type }}]"
    needs: [compile-lib]
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: alpine
            version: 3.13
          - name: ubuntu
            version: 18.04
          - name: ubuntu
            version: 20.04
        compiler: [ clang, gcc ]
        compiler_version: [ 10 ]
        lib_type: [ shared, static ]
    steps:
      - uses: actions/checkout@v2
      - name: Download the Artifact
        uses: actions/download-artifact@v2
        with:
          name: xalwart.base-${{ matrix.lib_type }}-${{ matrix.os.name }}
          path: xalwart.base-${{ matrix.lib_type }}-${{ matrix.os.name }}
      - name: Build and Run Tests
        run: |
          sudo docker run -i \
                          -v ${{ github.workspace }}:/app \
                          xalwart/gtest:1.11.0-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.os.name }}-${{ matrix.os.version }} \
                          bash /app/misc/test.sh ${{ matrix.os.name }} ${{ matrix.lib_type }} ${{ matrix.compiler }}
