name: CI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  build_type: Release

jobs:
  build:
    name: ${{ matrix.name }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [Ubuntu]
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build Google Test Framework
        env:
          CC: gcc
          CXX: g++
        run: |
          sudo bash scripts/install_gtest.sh
      - name: Build Library
        env:
          CC: gcc
          CXX: g++
        run: |
          sudo mkdir lib-build
          cd lib-build
          sudo cmake ..
          sudo make
          sudo ./tests/unittests-all
