name: "ci"
on:
  pull_request:
  push:
    branches:
      - master
      - dev
jobs:
  compile-lib:
    name: Build the library and upload it to artifacts
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        lib_type: [ shared, static ]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Library
        run: |
          sudo docker run -i \
                          -v ${{ github.workspace }}:/app \
                          xalwart/gcc:10-alpine-3.13 \
                          bash /app/misc/build.sh alpine dev ${{ matrix.lib_type }}
      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xalwart.base-linux-dev-${{ matrix.lib_type }}
          path: xalwart.base-linux-dev-${{ matrix.lib_type }}
          retention-days: 90
  test:
    name: "${{ matrix.os }} [${{ matrix.compiler }}-${{ matrix.compiler_version }}] [${{ matrix.lib_type }}]"
    needs: [compile-lib]
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        os: [ "alpine-3.13", "ubuntu-18.04", "ubuntu-20.04" ]
        compiler: [ clang, gcc ]
        compiler_version: [ 10 ]
        lib_type: [ shared, static ]
    steps:
      - uses: actions/checkout@v2
      - name: Download the Artifact
        uses: actions/download-artifact@v2
        with:
          name: xalwart.base-linux-dev-${{ matrix.lib_type }}
          path: xalwart.base-linux-dev-${{ matrix.lib_type }}
      - name: Run Tests
        run: |
          sudo docker run -i \
                          -v ${{ github.workspace }}:/app \
                          xalwart/gtest:1.11.0-${{ matrix.compiler }}-${{ matrix.compiler_version }}-${{ matrix.os }} \
                          bash /app/misc/test.sh ${{ matrix.os }} dev ${{ matrix.lib_type }}
