name: Continuous Integration

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  build_type: Release

jobs:
  build:
    name: ${{ matrix.name }} - ${{ matrix.os }} - ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [Ubuntu]
        os: [ubuntu-16.04, ubuntu-18.04]
        compiler: [g++-7]
    steps:
      - uses: actions/checkout@v2

      - name: Install g++ and Check Version
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          sudo apt update -y && \
          sudo apt install -y ${{ matrix.compiler }} && \
          g++ --version

      - name: Install and Build Google Test Framework
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          sudo bash scripts/install_gtest.sh

      - name: Build the Library
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          sudo mkdir build-debug && \
          cd build-debug/ && \
          sudo cmake -DCMAKE_BUILD_TYPE=Debug .. && \
          sudo make

      - name: Run Tests
        run: |
          cd build-debug/ && \
          sudo ./tests/unittests-all
