name: Countinues Integrtion

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  build_type: Release

jobs:
  build:
    name: ${{ matrix.name }} - ${{ matrix.os }} - ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [Ubuntu]
        os: [ubuntu-16.04, ubuntu-18.04]
        compiler: [g++]
    steps:
      - uses: actions/checkout@v2

      - name: Check g++ version
        run: |
          g++ --version

      - name: Install and Build Google Test Framework
        run: |
          sudo git clone -q https://github.com/google/googletest.git googletest/ && \
          sudo mkdir -p googletest/build && \
          cd googletest/build && \
          sudo cmake .. && \
          make && \
          make install && \
          cd / && \
          sudo rm -rf googletest/

      - name: Build the Library
        run: |
          sudo mkdir build-debug/ && \
          cd build-debug/ && \
          sudo cmake -DCMAKE_BUILD_TYPE=Debug .. && \
          sudo make

      - name: Run Tests
        run: |
          cd build-debug/ && \
          sudo ./tests/unittests-all
