name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get install libgtest-dev
          cd /usr/src/googletest/googletest || exit
          sudo mkdir build
          cd build || exit
          sudo cmake ..
          sudo make
          sudo cp libgtest* /usr/lib/
          cd ..
          sudo rm -rf build
          sudo mkdir /usr/local/lib/googletest
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/googletest/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/googletest/libgtest_main.a
          sudo mkdir build
          cd build
          sudo cmake ..
          sudo make
          ./tests/unittests-all
