name: "alpine-gcc"
on:
  push:
    branches:
      - 'alpine/*'
      - 'alpine-*'
      - 'testing'
      - 'dev'
jobs:
  build:
    name: "alpine-${{ matrix.alpine_version }} [gcc-10]"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        alpine_version: [3.13]
    steps:
      - uses: actions/checkout@v2
      - name: Build the Container
        run: |
          sudo docker build --build-arg alpine_version=${{ matrix.alpine_version }} \
                            -f docker/alpine/gcc.Dockerfile \
                            --tag=xalwart.core-test:alpine-gcc .
      - name: Run Tests
        run: |
          sudo docker run xalwart.core-test:alpine-gcc
