name: "alpine-clang"
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  build:
    name: "alpine-${{ matrix.alpine_version }} [clang-10]"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        alpine_version: [3.13]
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: |
          sudo docker build --build-arg alpine_version=${{ matrix.alpine_version }} \
                            -f docker/alpine/clang.Dockerfile \
                            --tag=xalwart.core-test:alpine-clang . && \
      - name: Run tests
        run: |
          sudo docker run xalwart.core-test:alpine-clang
